tasks:
  - name: Install
    command: |
      npm ci

      gp sync-done install

      exit 0
  - name: Setup
    before: |
      curl -sfL gpm.simonemms.com | bash

      gpm install pre-commit

      pip install cookieninja cruft

      gp sync-done setup

      pre-commit install --install-hooks -t pre-commit -t commit-msg

      gp sync-done pre-commit

      exit 0
  - command: |
      gp sync-await setup
      gp sync-await install

      {%- if cookiecutter.type == "nestjs" %}
      docker-compose up app
      {%- elif cookiecutter.type == "svelte" %}
      {%- endif %}

vscode:
  extensions:
    - donjayamanne.git-extension-pack
    - EditorConfig.EditorConfig
    - waderyan.gitblame
    - GitHub.vscode-github-actions
    - ms-vscode.makefile-tools
    {%- if cookiecutter.type == "svelte" %}
    - svelte.svelte-vscode
    {%- endif %}
